#!/bin/bash
TIME=$(date +%Y-%m-%d-%T)
while true; do
for i in 192.168.137{101..103} #IP address clusters, if connection refuse, then resourse - down
do ping -c 1 $i > /dev/null
if [ $? -eq 0 ]; then
echo Connection established $i $TIME >> /var/log/connection && sudo pcs resource enable VIP --node "$HOSTNAME" #VIP - group resourse or one resourse
elif [ $? -ne 0 ]; then
echo Host $i Unreachable $TIME >> /var/log/connection && sudo pcs resourse disable VIP --node "$HOSTNAME"
fi
done
sleep 5 #Timeout before launch resource 30 sec
done
